import os
import glob
from zipfile import ZipFile

ASSIGNEMENT = "Assignment1"


def main() -> None:
    # get filenames starting with ex
    file_names = glob.glob(f"{os.path.join(os.getcwd(),ASSIGNEMENT)}/ex*")
    # create the name according to their convention
    target_file = f"{ASSIGNEMENT}/FlückigerManuel_PalapurackalDeepak_{ASSIGNEMENT}.py"

    # Generate file head
    output = open(target_file,"w")
    output.write("# This file is automatically generated from the exercise files. For more information visit: https://github.com/M4anuel/FS24-Programming-For-Datasciences\n__author__ = \"Flueckiger Manuel and Palapurackal Deepak\"\n\n")
    
    # Generate file body containing exercises
    for file_name in file_names:
        with open(file_name, "r") as file:
            # Read the contents of the file or perform any other actions
            content = file.read()
            output.write("\n# ")
            output.write(os.path.basename(file_name))
            output.write("\n")
            output.write(content)
            output.write("\n")
    output.close()

    # zip it
    with ZipFile(f"{ASSIGNEMENT}/FlückigerManuel_PalapurackalDeepak.zip", 'w') as zip:
            zip.write(target_file)


if __name__ == "__main__":
    main()