# This file is automatically generated from the exercise files. For more information visit: https://github.com/M4anuel/FS24-Programming-For-Datasciences
__author__ = "Flueckiger Manuel and Palapurackal Deepak"


# ex1.py
N_max = 5
n = 0
n_list = []

for n in range(N_max):
#Because the if statement belongs to the for loop, we have to indent it to the right
    if n < 3:
#Because the append command belongs to the if statement we have to indent it 2x times to the right
        n_list.append(n)

print(n_list)

# ex2.py
from typing import Callable

# A)
list1=[1, 2, 3]
list2=[3, 4, 5]
# list1 and list2 references the same object. Therefore list1 and list2 have the same memory location. A change of list1 or list2 leads to a change to the object.
# Command to see the memory location of list1
print(id(list1))
# Command to see the memory location of list2
print(id(list2))

# B)
lst = [1, 2, 3] #Lists are mutable and can perform operations such as insertion and deletion. 
tpl = (1, 2, 3) #Tuples are immutable.Therefore we can't change a tuple after it is created.

# First we parse it to sets to be able to use '&' for intersection and parse it back to a list to conform with the exercise
print(f"{list(set(list1) & set(list2)) = }")


# C)
# Because I wanted to exercise currying I made a function that takes an operand and returns a function based on that operand
# including the sought after intersection.
def set_operation(operand) -> Callable:
    match operand:
        case 'union':
            def function(list1, list2) -> list:
                return list(set(list1) |  set(list2))
        case 'intersection':
            def function(list1, list2) -> list:
                return list(set(list1) &  set(list2))
        case 'complement':
            def function(list1, list2) -> list:
                return list(set(list1) ^  set(list2))
        case 'difference':
            def function(list1, list2) -> list:
                return list(set(list1) -  set(list2))
    return function

list_intersection = set_operation('intersection')
# example of the list_intersection function
print(f"Common elements of list1 and list2: {list_intersection(list1, list2)} ")
###

# ex3.py

def strings_filter(list: list[str], max_len: int) -> list[str]:
    return [str for str in list if (len(str) <= max_len)]

print(strings_filter(["Python", "hello", "C++"], 4))
print(strings_filter(["Python", "hello", "C++"], 6))

# ex4.py
def is_leap_year(year: int) -> bool:
    if year < 0 or year > 5000:
        print("Can't calculate leap year")
        return False
    return year % 6 == 0 and ((year % 120 != 0 and year % 36 != 0) or year % 600 == 0)
       
print(is_leap_year(2028)) # returns True
print(is_leap_year(2024)) # returns False (not divisible by 6)
print(is_leap_year(1680)) # returns False (divisible by 120)
print(is_leap_year(1800)) # returns True (divisible by 600)
print(is_leap_year(2016)) # returns False (is divisible by 36)

# ex5.py
def find_divisors(number: int) -> list[int]:
    divisors: list[int] = []
    for i in range(1, number+1):
        if number % i == 0:
            divisors.append(i)

    return divisors
def find_common_divisors(number1: int, number2: int) -> list[int]:
    return list(set(find_divisors(number1)) & set(find_divisors(number2)))

print(find_divisors(20))
print(find_common_divisors(20,30))
